export const ROUTES = {
    HOME: "/",
    SIGNIN: "/signIn",
    SIGNUP: "/signUp",
    ABOUT: "/about",
    AWARENESS: "/awareness",
    DONATE: "/donate",
    DONATION_GUIDE: "/donation-guide",
    STORIES: "/stories",
    DONOR_DASHBOARD: "/donor-dashboard",
    ADMIN_DASHBOARD: "/admin",
    SOCIAL_WORKER_DASHBOARD: "/social-worker",
    SUPPORT_REQUEST: "/support-requests",
    ADMIN_HOME: "/admin/home",
    ALL_PATIENTS: "/admin/patients",
    DONATION_USAGE: "/admin/donation-usage",
    MAKE_REQUEST: "/admin/make-request",
    
    // SUPPORT_REQUEST: "/support-request",
    MANAGE_DONATION_REQUESTS: "/admin/manage-donation-requests",
    DONATIONS: "/admin/donations",
    RECEIVED_DONATION : "/admin/donations/received-donations",
};
