export const END_POINTS = {
  LOGIN: "api/users/login",
  GET_ALL_USERS: "api/users/all",
  GET_DONOR_PROFILE: "api/donors/profile",
  UPDATE_DONOR_PROFILE: "api/donors/profile",
  DELETE_DONOR_PROFILE: "api/donors/profile",
  CREATE_DONATION_REQUEST: "api/donation-requests",
  GET_DONOR_DONATION_REQUESTS: "api/donation-requests/donor",
  ADD_PATIENT: "api/patients/add-patient",
  GET_PATIENTS: "api/patients/get-patients",
  GET_PATIENT_BY_ID: (id) => `api/patients/get-patient/${id}`,
  UPDATE_PATIENT: (id) => `api/patients/update-patient/${id}`,
  DELETE_PATIENT: (id) => `api/patients/delete-patient/${id}`,
  GET_SUPPORT_REQUESTS: "api/support-requests/all",
  GET_SUPPORT_REQUEST_BY_ID: (id) => `api/support-requests/${id}`,
  ADD_SUPPORT_REQUEST: "api/support-requests/add",
  UPDATE_SUPPORT_REQUEST: (id) => `api/support-requests/update/${id}`,
  DELETE_SUPPORT_REQUEST: (id) => `api/support-requests/delete/${id}`,
};
